name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: 
  - MrAlders0n
body:  
  - type: textarea
    id: what-happened
    attributes:
      label:  What happened?
      description:  Describe the bug in a few sentences
      placeholder: Tell us what went wrong
    validations: 
      required: true
  
  - type: textarea
    id: steps
    attributes:  
      label: How to reproduce
      description: Quick steps to reproduce the issue
      placeholder: |
        1. Go to... 
        2. Click... 
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label:  What should happen instead?
      placeholder: Describe what you expected
    validations:
      required:  true
  
  - type:  dropdown
    id: severity
    attributes:
      label: How bad is it?
      options:
        - "Critical - Can't use it"
        - "High - Major problem"
        - "Medium - Annoying but workable"
        - "Low - Minor issue"
    validations: 
      required: true
  
  - type: textarea
    id: extra
    attributes:
      label:  Anything else?
      description: Screenshots, device info, browser, etc.
      placeholder: Add screenshots or extra details here